//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MMService.h"

#import "MMService.h"

@class NSString;

@interface WAPackagePredownloadMgr : MMService <MMService>
{
    _Bool _isSetupPackage;
}

@property(nonatomic) _Bool isSetupPackage; // @synthesize isSetupPackage=_isSetupPackage;
- (_Bool)presetupLaunchWithResponseString:(id)arg1 appId:(id)arg2;
- (_Bool)presetupContactWithResponseString:(id)arg1 userName:(id)arg2;
- (void)presetupDataWithContactResponseString:(id)arg1 launchResponseString:(id)arg2 userName:(id)arg3 appId:(id)arg4;
- (void)reportWithKey:(unsigned int)arg1;
- (void)copyBundlePackage:(id)arg1;
- (id)generatePredownloadInfoFromBundle;
- (id)getPredownloadInfoXml;
- (void)markSetupPredownloadPackage;
- (void)loadSetupPackageRecord;
- (id)pathOfSetupPackageRecord;
- (void)setupPackageDataFromLocalBundle;
- (void)clearSetupPredownloadPackage;
- (void)onServiceClearData;
- (void)onServiceReloadData;
- (void)onServiceInit;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

