//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class WAWhatsNewConfig;

@interface WAWhatsNewInfo : NSObject
{
    WAWhatsNewConfig *_config;
}

@property(retain, nonatomic) WAWhatsNewConfig *config; // @synthesize config=_config;
- (void).cxx_destruct;
- (id)description;

@end

